# Generated by Django 2.2.13 on 2020-06-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200626_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
