# Generated by Django 2.2.13 on 2020-07-03 07:41

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_closet_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='image',
            field=models.ImageField(blank=True, upload_to=pages.models.closet_image_path),
        ),
    ]
